# Generated by Django 5.1.3 on 2024-12-20 15:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_city_product_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='phone_number',
            field=models.CharField(default='phone_number', help_text='Enter a valid phone number starting with 092, 091, 094, or 093.', max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must start with 092, 091, 094, or 093 and be 10 digits long.', regex='^(092|091|094|093)\\d{7}$')]),
            preserve_default=False,
        ),
    ]
