# Generated by Django 4.2.4 on 2024-12-29 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_rating_delete_review'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together=set(),
        ),
    ]
