# Generated by Django 4.2.4 on 2025-01-25 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_reservation'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together=set(),
        ),
    ]
